const APP_VERSION="v1.0.0";
const SAFE_OBJECT_POSITIONS=[{x:15,y:18},{x:28,y:28},{x:43,y:18},{x:62,y:26},{x:79,y:20},{x:18,y:55},{x:38,y:60},{x:63,y:58},{x:82,y:62},{x:24,y:80},{x:52,y:78},{x:78,y:82}];
let story=null,scenes=[],currentScene=0,completed=new Set(),narrationEnabled=true,musicEnabled=true,currentNarration=null,currentMusic=null,coverTimer=null,coverPoseIndex=0;
const cover=document.getElementById("cover"),reader=document.getElementById("reader"),startBtn=document.getElementById("startBtn"),homeBtn=document.getElementById("homeBtn"),coverCatButton=document.getElementById("coverCatButton"),coverCat=document.getElementById("coverCat"),purrText=document.getElementById("purrText"),dedication=document.getElementById("dedication"),prevBtn=document.getElementById("prevBtn"),nextBtn=document.getElementById("nextBtn"),musicBtn=document.getElementById("musicBtn"),narrationBtn=document.getElementById("narrationBtn"),sceneCounter=document.getElementById("sceneCounter"),sceneText=document.getElementById("sceneText"),sceneHint=document.getElementById("sceneHint"),rewardText=document.getElementById("rewardText"),backgroundImage=document.getElementById("backgroundImage"),charactersLayer=document.getElementById("charactersLayer"),objectsLayer=document.getElementById("objectsLayer"),effectsLayer=document.getElementById("effectsLayer"),stage=document.getElementById("stage"),versionText=document.getElementById("versionText");
const coverPoses=Array.from({length:8},(_,i)=>`assets/ui/portada-zacarias/pose-${String(i+1).padStart(2,"0")}.png`);
const purrAudio=new Audio("assets/sfx/purr.mp3");purrAudio.volume=.65;
async function init(){try{const r=await fetch(`stories/cuento-zacarias.json?v=${Date.now()}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);story=await r.json();scenes=story.scenes||[];dedication.textContent=story.meta?.dedication||"";versionText.textContent=`Motor Zacarías ${story.meta?.version||APP_VERSION}`}catch(e){console.error("No se pudo cargar el cuento:",e);sceneText.innerHTML="<p>No se pudo cargar el cuento.</p>";return}startCoverAnimation();renderScene(0)}
function startCoverAnimation(){stopCoverAnimation();coverPoseIndex=0;const n=()=>{coverPoseIndex=(coverPoseIndex+1)%coverPoses.length;coverCat.src=coverPoses[coverPoseIndex];const d=[2200,450,1800,450,2500,220,1800,700][coverPoseIndex]||1200;coverTimer=setTimeout(n,d)};coverTimer=setTimeout(n,2200)}
function stopCoverAnimation(){if(coverTimer){clearTimeout(coverTimer);coverTimer=null}}
function renderScene(index){if(!scenes.length)return;stopNarration();currentScene=Math.max(0,Math.min(index,scenes.length-1));const s=scenes[currentScene];sceneCounter.textContent=`Página ${currentScene+1} de ${scenes.length}`;sceneText.innerHTML=(s.text||[]).map(x=>`<p>${x}</p>`).join("");sceneHint.textContent=s.hint||"";rewardText.textContent=completed.has(s.id)?"⭐ Descubrimiento logrado":"";renderBackground(s);renderCharacters(s);renderObjects(s);setupStageInteraction(s);playSceneAudio(s);prevBtn.style.visibility=currentScene===0?"hidden":"visible";nextBtn.style.visibility=currentScene===scenes.length-1?"hidden":"visible"}
function renderBackground(s){backgroundImage.src=`assets/backgrounds/${s.background}`;backgroundImage.onerror=()=>{backgroundImage.removeAttribute("src");stage.style.background="linear-gradient(135deg,#fff0c9,#e6b36f)"}}
function renderCharacters(s){charactersLayer.innerHTML="";(s.characters||[]).forEach(c=>{const img=document.createElement("img");img.className="scene-character";img.alt=c.name||"Personaje";img.src=`assets/characters/${c.folder}/${c.image}`;img.style.left=`${c.x??50}%`;img.style.top=`${c.y??88}%`;img.style.width=`${c.width??28}%`;img.onerror=()=>img.remove();img.addEventListener("click",ev=>{ev.stopPropagation();img.animate([{transform:"translate(-50%,-100%) rotate(0deg) scale(1)"},{transform:"translate(-50%,-100%) rotate(-5deg) scale(1.04)"},{transform:"translate(-50%,-100%) rotate(5deg) scale(1.04)"},{transform:"translate(-50%,-100%) rotate(0deg) scale(1)"}],{duration:800,easing:"ease-in-out"});playPurr();completeScene(s.id)});charactersLayer.appendChild(img)})}
function renderObjects(s){objectsLayer.innerHTML="";(s.objects||[]).forEach(o=>{const p=o.random?randomSafePosition():{x:o.x??50,y:o.y??55};const img=document.createElement("img");img.className="scene-object";img.alt=o.name||"Objeto escondido";img.src=`assets/objects/${o.image}`;img.style.left=`${p.x}%`;img.style.top=`${p.y}%`;img.style.width=`${o.width??12}%`;img.onerror=()=>{const n=document.createElement("span");n.className="missing-asset";n.textContent=`Falta: ${o.image}`;n.style.left=`${p.x}%`;n.style.top=`${p.y}%`;objectsLayer.appendChild(n);img.remove()};img.addEventListener("click",ev=>{ev.stopPropagation();img.classList.add("found");completeScene(s.id);setTimeout(()=>img.remove(),650)});objectsLayer.appendChild(img)})}
function randomSafePosition(){return SAFE_OBJECT_POSITIONS[Math.floor(Math.random()*SAFE_OBJECT_POSITIONS.length)]}
function setupStageInteraction(s){stage.onclick=null;if(s.interaction==="falling_leaves"){stage.onclick=()=>{createLeaves();completeScene(s.id)}}}
function completeScene(id){completed.add(id);rewardText.textContent="⭐ ¡Muy bien!";stage.animate([{filter:"brightness(1)"},{filter:"brightness(1.18)"},{filter:"brightness(1)"}],{duration:650})}
function playPurr(){try{purrAudio.currentTime=0;purrAudio.play()}catch(e){}}
function createLeaves(){effectsLayer.innerHTML="";const a=["🍂","🍁","🍃"];for(let i=0;i<12;i++){const s=document.createElement("span");s.className="particle";s.textContent=a[i%a.length];s.style.left=`${5+Math.random()*90}%`;s.style.top=`${Math.random()*8}%`;s.style.animationDelay=`${Math.random()*.6}s`;effectsLayer.appendChild(s)}setTimeout(()=>effectsLayer.innerHTML="",2500)}
function playSceneAudio(s){if(musicEnabled&&s.music){if(!currentMusic||!currentMusic.src.endsWith(s.music)){stopMusic();currentMusic=new Audio(`assets/music/${s.music}`);currentMusic.loop=true;currentMusic.volume=.12;currentMusic.play().catch(()=>{})}}if(narrationEnabled&&s.narration){currentNarration=new Audio(`assets/narration/${s.narration}`);currentNarration.volume=1;currentNarration.play().catch(()=>{})}}
function stopNarration(){if(currentNarration){currentNarration.pause();currentNarration=null}}
function stopMusic(){if(currentMusic){currentMusic.pause();currentMusic=null}}
coverCatButton.addEventListener("click",()=>{coverCatButton.classList.add("rub");purrText.textContent="Prrrrrrrr...";playPurr();setTimeout(()=>{coverCatButton.classList.remove("rub");purrText.textContent=""},1900)});
startBtn.addEventListener("click",()=>{stopCoverAnimation();cover.classList.add("hidden");reader.classList.remove("hidden");renderScene(0)});
homeBtn.addEventListener("click",()=>{stopNarration();stopMusic();reader.classList.add("hidden");cover.classList.remove("hidden");startCoverAnimation()});
prevBtn.addEventListener("click",()=>renderScene(currentScene-1));nextBtn.addEventListener("click",()=>renderScene(currentScene+1));
musicBtn.addEventListener("click",()=>{musicEnabled=!musicEnabled;musicBtn.textContent=musicEnabled?"🎵":"🔕";if(musicEnabled)playSceneAudio(scenes[currentScene]);else stopMusic()});
narrationBtn.addEventListener("click",()=>{narrationEnabled=!narrationEnabled;narrationBtn.textContent=narrationEnabled?"🔊":"🔇";if(narrationEnabled)playSceneAudio(scenes[currentScene]);else stopNarration()});
init();